/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteRouteImport } from './routes/onboarding/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthSignupRouteRouteImport } from './routes/_auth/signup/route'
import { Route as AuthSigninRouteRouteImport } from './routes/_auth/signin/route'
import { Route as AppSettingsRouteRouteImport } from './routes/_app/settings/route'
import { Route as AppProfileRouteRouteImport } from './routes/_app/profile/route'
import { Route as AppMessagesRouteRouteImport } from './routes/_app/messages/route'
import { Route as AppDashboardRouteRouteImport } from './routes/_app/dashboard/route'
import { Route as AppBuddyFinderRouteRouteImport } from './routes/_app/buddy-finder/route'
import { Route as AppGoalsIndexRouteImport } from './routes/_app/goals/index'
import { Route as AppGoalsIdRouteImport } from './routes/_app/goals/$id'

const OnboardingRouteRoute = OnboardingRouteRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRouteRoute = AuthSignupRouteRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSigninRouteRoute = AuthSigninRouteRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AppSettingsRouteRoute = AppSettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppProfileRouteRoute = AppProfileRouteRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppMessagesRouteRoute = AppMessagesRouteRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDashboardRouteRoute = AppDashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppBuddyFinderRouteRoute = AppBuddyFinderRouteRouteImport.update({
  id: '/buddy-finder',
  path: '/buddy-finder',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppGoalsIndexRoute = AppGoalsIndexRouteImport.update({
  id: '/goals/',
  path: '/goals/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppGoalsIdRoute = AppGoalsIdRouteImport.update({
  id: '/goals/$id',
  path: '/goals/$id',
  getParentRoute: () => AppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRouteRoute
  '/buddy-finder': typeof AppBuddyFinderRouteRoute
  '/dashboard': typeof AppDashboardRouteRoute
  '/messages': typeof AppMessagesRouteRoute
  '/profile': typeof AppProfileRouteRoute
  '/settings': typeof AppSettingsRouteRoute
  '/signin': typeof AuthSigninRouteRoute
  '/signup': typeof AuthSignupRouteRoute
  '/goals/$id': typeof AppGoalsIdRoute
  '/goals': typeof AppGoalsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRouteRoute
  '/buddy-finder': typeof AppBuddyFinderRouteRoute
  '/dashboard': typeof AppDashboardRouteRoute
  '/messages': typeof AppMessagesRouteRoute
  '/profile': typeof AppProfileRouteRoute
  '/settings': typeof AppSettingsRouteRoute
  '/signin': typeof AuthSigninRouteRoute
  '/signup': typeof AuthSignupRouteRoute
  '/goals/$id': typeof AppGoalsIdRoute
  '/goals': typeof AppGoalsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteRouteWithChildren
  '/_auth': typeof AuthRouteRouteWithChildren
  '/onboarding': typeof OnboardingRouteRoute
  '/_app/buddy-finder': typeof AppBuddyFinderRouteRoute
  '/_app/dashboard': typeof AppDashboardRouteRoute
  '/_app/messages': typeof AppMessagesRouteRoute
  '/_app/profile': typeof AppProfileRouteRoute
  '/_app/settings': typeof AppSettingsRouteRoute
  '/_auth/signin': typeof AuthSigninRouteRoute
  '/_auth/signup': typeof AuthSignupRouteRoute
  '/_app/goals/$id': typeof AppGoalsIdRoute
  '/_app/goals/': typeof AppGoalsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/onboarding'
    | '/buddy-finder'
    | '/dashboard'
    | '/messages'
    | '/profile'
    | '/settings'
    | '/signin'
    | '/signup'
    | '/goals/$id'
    | '/goals'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/onboarding'
    | '/buddy-finder'
    | '/dashboard'
    | '/messages'
    | '/profile'
    | '/settings'
    | '/signin'
    | '/signup'
    | '/goals/$id'
    | '/goals'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_auth'
    | '/onboarding'
    | '/_app/buddy-finder'
    | '/_app/dashboard'
    | '/_app/messages'
    | '/_app/profile'
    | '/_app/settings'
    | '/_auth/signin'
    | '/_auth/signup'
    | '/_app/goals/$id'
    | '/_app/goals/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  OnboardingRouteRoute: typeof OnboardingRouteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/signup': {
      id: '/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthSignupRouteRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/signin': {
      id: '/_auth/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof AuthSigninRouteRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/messages': {
      id: '/_app/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof AppMessagesRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/buddy-finder': {
      id: '/_app/buddy-finder'
      path: '/buddy-finder'
      fullPath: '/buddy-finder'
      preLoaderRoute: typeof AppBuddyFinderRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/goals/': {
      id: '/_app/goals/'
      path: '/goals'
      fullPath: '/goals'
      preLoaderRoute: typeof AppGoalsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/goals/$id': {
      id: '/_app/goals/$id'
      path: '/goals/$id'
      fullPath: '/goals/$id'
      preLoaderRoute: typeof AppGoalsIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppBuddyFinderRouteRoute: typeof AppBuddyFinderRouteRoute
  AppDashboardRouteRoute: typeof AppDashboardRouteRoute
  AppMessagesRouteRoute: typeof AppMessagesRouteRoute
  AppProfileRouteRoute: typeof AppProfileRouteRoute
  AppSettingsRouteRoute: typeof AppSettingsRouteRoute
  AppGoalsIdRoute: typeof AppGoalsIdRoute
  AppGoalsIndexRoute: typeof AppGoalsIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppBuddyFinderRouteRoute: AppBuddyFinderRouteRoute,
  AppDashboardRouteRoute: AppDashboardRouteRoute,
  AppMessagesRouteRoute: AppMessagesRouteRoute,
  AppProfileRouteRoute: AppProfileRouteRoute,
  AppSettingsRouteRoute: AppSettingsRouteRoute,
  AppGoalsIdRoute: AppGoalsIdRoute,
  AppGoalsIndexRoute: AppGoalsIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthSigninRouteRoute: typeof AuthSigninRouteRoute
  AuthSignupRouteRoute: typeof AuthSignupRouteRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthSigninRouteRoute: AuthSigninRouteRoute,
  AuthSignupRouteRoute: AuthSignupRouteRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  OnboardingRouteRoute: OnboardingRouteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
